### ISSUE TITLE
Compile In GCC 4.8.1 32-bit

### ISSUE THREAD

**Issue by iplanc** [EZForever/libCanvas#1]
```
D:\用户目录\我的文档\Demo.c	In function 'ClickCB':
7	3	D:\用户目录\我的文档\Demo.c	[Warning] incompatible implicit declaration of built-in function 'printf' [enabled by default]
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x30): undefined reference to `QBColor'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x65): undefined reference to `cvsPrint'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x70): undefined reference to `cvsRefresh'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0xac): undefined reference to `cvsCreate'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0xbc): undefined reference to `QBColor'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0xcc): undefined reference to `cvsClear'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0xf0): undefined reference to `cvsSetPx'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0xfc): undefined reference to `QBColor'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x12c): undefined reference to `cvsLine'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x138): undefined reference to `QBColor'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x170): undefined reference to `cvsRect'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x17c): undefined reference to `QBColor'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x1b4): undefined reference to `cvsRect'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x1f0): undefined reference to `cvsPrint'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x1fc): undefined reference to `QBColor'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x234): undefined reference to `cvsPrint'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x25e): undefined reference to `cvsRefresh'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x272): undefined reference to `cvsShow'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x27c): undefined reference to `cvsIOInit'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x298): undefined reference to `cvsSave'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x2ac): undefined reference to `cvsClear'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x2b8): undefined reference to `cvsRefresh'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x2d1): undefined reference to `cvsLoad'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x2dd): undefined reference to `cvsRefresh'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x2e7): undefined reference to `cvsIOUninit'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x2fb): undefined reference to `cvsShow'
C:\Users\ADMINI~1\AppData\Local\Temp\ccNzTpYH.o	Demo.c:(.text+0x307): undefined reference to `cvsDestroy'
```

**Comment by iplanc** [comment]
IDE DevCPP

**Comment by EZForever** [comment]
使用IDE编译的话需要在工程设置中指定链接libCanvas库的，请参考IDE帮助。
或者手动编译，命令行参考Demo.c第一行的注释。
